### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by matu3ba** [BrookJeynes/listings-zig#1]
```diff
-    var it = std.mem.tokenize(u8, input, " ,");
+    var it = std.mem.tokenize(u8, input, " ");
```

**Comment by BrookJeynes** [comment]
As per the [code example](https://ziglang.org/) on the front-page, this is not a type.

<img width="1033" alt="image" src="https://github.com/BrookJeynes/listings-zig/assets/25432120/133b11ac-f4d6-4669-b6e8-c48a41244c9d">
